### ISSUE TITLE
Compiling error of the dvs_ros_driver

### ISSUE THREAD

**Issue by doomzzju** [uzh-rpg/rpg_dvs_ros#10]
Hi guys, I'm trying to compile the rpg_dvs_ros package these day. When I compiled the dvs_ros_driver, there is a error just like below:

/opt/ros/indigo/lib/libcamera_calibration_parsers.so: undefined reference to `YAML::detail::node_data::convert_to_map(boost::shared_ptrYAML::detail::memory_holder)'

How can I fix this bug? thanks~~

**Comment by eliasm** [comment]
Could you give some more details? Which package causes the error? What version of ROS and Ubuntu are you using?

**Comment by doomzzju** [comment]
I use ROS indigo and Ubuntu 14.04. The  package dvs_ros_driver causes this error, it seems like something about YAML?

**Comment by eliasm** [comment]
Are you also using the `yaml_cpp_catkin` package from ETH/ASL? If so, please update that package to the latest version, clean your entire workspace, and build everything again.
