### ISSUE TITLE
Error using DAVIS driver as nodelet

### ISSUE THREAD

**Issue by alexzzhu** [uzh-rpg/rpg_dvs_ros#11]
The DAVIS ROS driver currently clears the event array within the message immediately after publishing. This seems to cause problems when the driver is run as a nodelet as the subscriber receives a pointer to the original message, which now has an empty event array. Storing the event array in a separate variable which is copied into the message and then cleared seems to resolve the issue.

**Comment by eliasm** [comment]
Thanks, @alexzzhu! It would be great if you could create a pull request with the change.

**Comment by eliasm** [comment]
thanks, @morloy
