### ISSUE TITLE
The image time difference of sychronized davis346

### ISSUE THREAD

**Issue by HiOtto** [uzh-rpg/rpg_dvs_ros#113]
Connect the cameras as the desciption in datasheet
![Screenshot from 2020-12-05 13-07-42](https://user-images.githubusercontent.com/6235403/101234519-ed8b8600-36fa-11eb-9a48-08c4a592f574.png)
Disabled the event stream for descreasing data transmission pressure, actually the image time difference also appears when event is enable. 
And the settings detail is followed:
```
{DiffBn_coarse: 4, DiffBn_fine: 39, OFFBn_coarse: 4, OFFBn_fine: 0, ONBn_coarse: 6,
  ONBn_fine: 200, PrBp_coarse: 2, PrBp_fine: 58, PrSFBp_coarse: 1, PrSFBp_fine: 33,
  RefrBp_coarse: 4, RefrBp_fine: 25, aps_enabled: true, dvs_enabled: false, exposure: 6000,
  frame_interval: 40000,
  imu_acc_scale: 3, imu_enabled: true, imu_gyro_scale: 3, max_events: 0,
  streaming_rate: 30}
```
And also the driver print info hits they have been successfully connected
```
[ WARN] [1607110461.194875304]: Requested serial number: AAAAAAAA
[ WARN] [1607110461.198470133]: Requested serial number: BBBBBBBB
[ INFO] [1607110461.206421489]: DAVIS ID-1 SN-AAAAAAAA [2:14] --- ID: 1, Master: 0, DVS X: 346, DVS Y: 260, Logic: 6.

[ INFO] [1607110461.542280818]: using default calibration URL
[ INFO] [1607110461.542336931]: camera calibration URL: file:///home/sq/.ros/camera_info/DAVIS-AAAAAAAA.yaml
[ INFO] [1607110461.542398283]: Unable to open camera calibration file [/home/sq/.ros/camera_info/DAVIS-AAAAAAAA.yaml]
[ WARN] [1607110461.542424106]: Camera calibration file /home/sq/.ros/camera_info/DAVIS-AAAAAAAA.yaml not found.
[ INFO] [1607110461.806291732]: DAVIS ID-1 SN-BBBBBBBB [1:8] --- ID: 1, Master: 1, DVS X: 346, DVS Y: 260, Logic: 6.

[ INFO] [1607110461.864607078]: Reset timestamps on DAVIS-AAAAAAAA to 1607110461.864578724.
[ INFO] [1607110462.142544293]: using default calibration URL
[ INFO] [1607110462.142585933]: camera calibration URL: file:///home/sq/.ros/camera_info/DAVIS-BBBBBBBB.yaml
[ INFO] [1607110462.142658685]: Unable to open camera calibration file [/home/sq/.ros/camera_info/DAVIS-BBBBBBBB.yaml]
[ WARN] [1607110462.142691755]: Camera calibration file /home/sq/.ros/camera_info/DAVIS-BBBBBBBB.yaml not found.
[ INFO] [1607110462.465738304]: Reset timestamps on DAVIS-BBBBBBBB to 1607110462.465708256.
[ INFO] [1607110462.465935727]: Adapting reset time of master on slave DAVIS-00000282.
[ INFO] [1607110462.471492271]: Started timer to reset timestamps on master DVS for synchronization (delay=2.00s).
[ INFO] [1607110464.471837374]: Reset timestamps on DAVIS-BBBBBBBB to 1607110464.471813679.
[ INFO] [1607110464.471951575]: Adapting reset time of master on slave DAVIS-AAAAAAAA.
```
The camera should be easily triggered together, but the image timestamps show a difference beyond  0.003s. 0.003s is the lowest difference I got, sometime even over 0.015s, which has the same magnitude with image frame interval 0.04s(25Hz).
In constract with image, imu data can be well aligned despite that imu rate is much higher than image.
![Screenshot from 2020-12-05 14-53-48](https://user-images.githubusercontent.com/6235403/101236220-562e2f00-370a-11eb-888e-486e83d7a260.png)
Is there any way to get the images triggered at the same time? It's not so difficult which connected device
I really cannot guess the hardware design and the soft processs of synchronization, can you please provide an more detail instruction rather than serval pin names for the user?

**Comment by llongi** [comment]
This is the expected behaviour. The synchronization between cameras only concerns the timestamps themselves, not any of the data stream contents.
Frames are not taken at the same time, and that IMU aligns in your case is pretty much a random effect, not by design.
The design goal of the synchronization was to relate events from different cameras to each-other correctly, and relate the other data streams (Frames, IMU, Triggers) to the events. Frame-to-Frame was not considered, and is not planned to be added in the near future to the device firmware.
