### ISSUE TITLE
Build Error Ubunto 20.04 ROS Noetic (libcaer)

### ISSUE THREAD

**Issue by MF-Ahmed** [uzh-rpg/rpg_dvs_ros#145]
Hi,
I am having the following error. 

Errors     << dvs_ros_driver:cmake /home/usr/rpg_dvs_ros_ws/logs/dvs_ros_driver/build.cmake.000.log                                                                                                      
CMake Error at /home/usr/rpg_dvs_ros_ws/src/rpg_dvs_ros/dvs_ros_driver/CMakeLists.txt:5 (find_package):
  By not providing "Findlibcaer.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "libcaer", but
  CMake did not find one.

  Could not find a package configuration file provided by "libcaer" with any
  of the following names:

    libcaerConfig.cmake
    libcaer-config.cmake

  Add the installation prefix of "libcaer" to CMAKE_PREFIX_PATH or set
  "libcaer_DIR" to a directory containing one of the above files.  If
  "libcaer" provides a separate development package or SDK, be sure it has
  been installed.

cd /home/usr/rpg_dvs_ros_ws/build/dvs_ros_driver; catkin build --get-env dvs_ros_driver | catkin env -si  /usr/bin/cmake /home/usr/rpg_dvs_ros_ws/src/rpg_dvs_ros/dvs_ros_driver --no-warn-unused-cli -DCATKIN_DEVEL_PREFIX=/home/usr/rpg_dvs_ros_ws/devel -DCMAKE_INSTALL_PREFIX=/home/usr/rpg_dvs_ros_ws/install -DCMAKE_BUILD_TYPE=Release; cd -

.........................................................................................................................................................................................................
Failed     << dvs_ros_driver:cmake          [ Exited with code 1 ]                                                                                                                                       
Failed    <<< dvs_ros_driver                [ 0.7 seconds ]                                

Thanks

**Comment by benghalensis** [comment]
Hello,
How was this solved?
