### ISSUE TITLE
Stereo Calibration with DVS and RGB camera

### ISSUE THREAD

**Issue by Monopolymer** [uzh-rpg/rpg_dvs_ros#19]
I would like to make a stereo pair with a dvs128 and a standart rgb camera. would this be possible with this package? 
camera_dvs.launch to me seems to do this. is this correct?
if not what would be a god way to do it? i was thinking about putting my led grid on a circle pattern so the dvs and the rgb camera would see the same points. I also thought of replacing the find checkboardcorners so the rgb camera would find the leds.
any suggestions?
Thanks in advance.

**Comment by eliasm** [comment]
Yes, the file that you mention is intended to do this calibration. The blinking LEDs are then detected by simple thresholding on the intensity image. If there is a detection in both the camera image and the DVS event stream, a sample is added. You can also choose whether you want the change the intrinsic calibration of the camera and DVS, or you want to keep them fixed (calibrate them separately before). I would recommend the latter option (which is default). Please let me know if you have any problems using the package.
