### ISSUE TITLE
Branch fix/stereo catkin_make fails

### ISSUE THREAD

**Issue by gussmith** [uzh-rpg/rpg_dvs_ros#21]
branch master works fine, but branch fix/stereo now does not compile: 

rpg_dvs_ros/davis_ros_driver/CMakeFiles/davis_ros_driver.dir/src/driver_node.cpp.o
In file included from /opt/ros/kinetic/include/ros/serialization.h:37:0,
                 from /opt/ros/kinetic/include/ros/publisher.h:34,
                 from /opt/ros/kinetic/include/ros/node_handle.h:32,
                 from /opt/ros/kinetic/include/ros/ros.h:45,
                 from /home/odroid/catkin_ws/src/rpg_dvs_ros/davis_ros_driver/include/davis_ros_driver/driver.h:18,
                 from /home/odroid/catkin_ws/src/rpg_dvs_ros/davis_ros_driver/src/driver.cpp:16:
/opt/ros/kinetic/include/ros/message_traits.h: In instantiation of 'static const char* ros::message_traits::MD5Sum<M>::value(const M&) [with M = ros::Time]':
/opt/ros/kinetic/include/ros/message_traits.h:255:102:   required from 'const char* ros::message_traits::md5sum(const M&) [with M = ros::Time]'
/opt/ros/kinetic/include/ros/publisher.h:112:7:   required from 'void ros::Publisher::publish(const M&) const [with M = ros::Time]'
/home/odroid/catkin_ws/src/rpg_dvs_ros/davis_ros_driver/src/driver.cpp:189:35:   required from here
/opt/ros/kinetic/include/ros/message_traits.h:126:34: error: 'const class ros::Time' has no member named '__getMD5Sum'
     return m.__getMD5Sum().c_str();
                                  ^
/opt/ros/kinetic/include/ros/message_traits.h: In instantiation of 'static const char* ros::message_traits::DataType<M>::value(const M&) [with M = ros::Time]':
/opt/ros/kinetic/include/ros/message_traits.h:264:104:   required from 'const char* ros::message_traits::datatype(const M&) [with M = ros::Time]'
/opt/ros/kinetic/include/ros/publisher.h:112:7:   required from 'void ros::Publisher::publish(const M&) const [with M = ros::Time]'
/home/odroid/catkin_ws/src/rpg_dvs_ros/davis_ros_driver/src/driver.cpp:189:35:   required from here
/opt/ros/kinetic/include/ros/message_traits.h:143:36: error: 'const class ros::Time' has no member named '__getDataType'
     return m.__getDataType().c_str();
                                    ^
rpg_dvs_ros/davis_ros_driver/CMakeFiles/davis_ros_driver_nodelet.dir/build.make:86: recipe for target 'rpg_dvs_ros/davis_ros_driver/CMakeFiles/davis_ros_driver_nodelet.dir/src/driver.cpp.o' failed
make[2]: *** [rpg_dvs_ros/davis_ros_driver/CMakeFiles/davis_ros_driver_nodelet.dir/src/driver.cpp.o] Error 1
CMakeFiles/Makefile2:1665: recipe for target 'rpg_dvs_ros/davis_ros_driver/CMakeFiles/davis_ros_driver_nodelet.dir/all' failed
make[1]: *** [rpg_dvs_ros/davis_ros_driver/CMakeFiles/davis_ros_driver_nodelet.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 35%] Building CXX object rpg_dvs_ros/davis_ros_driver/CMakeFiles/davis_ros_driver.dir/src/driver.cpp.o
In file included from /opt/ros/kinetic/include/ros/serialization.h:37:0,
                 from /opt/ros/kinetic/include/ros/publisher.h:34,
                 from /opt/ros/kinetic/include/ros/node_handle.h:32,
                 from /opt/ros/kinetic/include/ros/ros.h:45,
                 from /home/odroid/catkin_ws/src/rpg_dvs_ros/davis_ros_driver/include/davis_ros_driver/driver.h:18,
                 from /home/odroid/catkin_ws/src/rpg_dvs_ros/davis_ros_driver/src/driver.cpp:16:
/opt/ros/kinetic/include/ros/message_traits.h: In instantiation of 'static const char* ros::message_traits::MD5Sum<M>::value(const M&) [with M = ros::Time]':
/opt/ros/kinetic/include/ros/message_traits.h:255:102:   required from 'const char* ros::message_traits::md5sum(const M&) [with M = ros::Time]'
/opt/ros/kinetic/include/ros/publisher.h:112:7:   required from 'void ros::Publisher::publish(const M&) const [with M = ros::Time]'
/home/odroid/catkin_ws/src/rpg_dvs_ros/davis_ros_driver/src/driver.cpp:189:35:   required from here
/opt/ros/kinetic/include/ros/message_traits.h:126:34: error: 'const class ros::Time' has no member named '__getMD5Sum'
     return m.__getMD5Sum().c_str();
                                  ^
/opt/ros/kinetic/include/ros/message_traits.h: In instantiation of 'static const char* ros::message_traits::DataType<M>::value(const M&) [with M = ros::Time]':
/opt/ros/kinetic/include/ros/message_traits.h:264:104:   required from 'const char* ros::message_traits::datatype(const M&) [with M = ros::Time]'
/opt/ros/kinetic/include/ros/publisher.h:112:7:   required from 'void ros::Publisher::publish(const M&) const [with M = ros::Time]'
/home/odroid/catkin_ws/src/rpg_dvs_ros/davis_ros_driver/src/driver.cpp:189:35:   required from here
/opt/ros/kinetic/include/ros/message_traits.h:143:36: error: 'const class ros::Time' has no member named '__getDataType'
     return m.__getDataType().c_str();
                                    ^
rpg_dvs_ros/davis_ros_driver/CMakeFiles/davis_ros_driver.dir/build.make:86: recipe for target 'rpg_dvs_ros/davis_ros_driver/CMakeFiles/davis_ros_driver.dir/src/driver.cpp.o' failed
make[2]: *** [rpg_dvs_ros/davis_ros_driver/CMakeFiles/davis_ros_driver.dir/src/driver.cpp.o] Error 1
CMakeFiles/Makefile2:1817: recipe for target 'rpg_dvs_ros/davis_ros_driver/CMakeFiles/davis_ros_driver.dir/all' failed
make[1]: *** [rpg_dvs_ros/davis_ros_driver/CMakeFiles/davis_ros_driver.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2
Invoking "make -j2" failed

**Comment by eliasm** [comment]
Thanks, the commits 5946dfd and 380d0e5 should fix this error.
