### ISSUE TITLE
branch master: [davis_ros_driver-1] process has died

### ISSUE THREAD

**Issue by gussmith** [uzh-rpg/rpg_dvs_ros#22]
Recent changes after install on new computer with Ubuntu 16.04 with ROS Kinetic causes the Davis driver to die right upon starting dvs_renderer using:

roslaunch dvs_renderer davis_mono_events_only.launch
or 
roslaunch dvs_renderer davis_mono.launch

Yet: davis_mono_nodelet.launch does work though

Error msg:
[davis_ros_driver-1] process has died [pid 27252, exit code -7, cmd /home/gus/catkin_rpg_master/devel/lib/davis_ros_driver/rdavis_ros_driver __name:=davis_ros_driver __log:=/home/gus/.ros/log/76c37878-128e-11e7-a827-d0577b49371b/davis_ros_driver-1.log].
log file: /home/gus/.ros/log/76c37878-128e-11e7-a827-d0577b49371b/davis_ros_driver-1*.log

Yet, the log file remains empty.

**Comment by luccide** [comment]
Having the exact same issue here

**Comment by eliasm** [comment]
Thanks for reporting this issue. Could you please check whether #24 resolves the issue?

**Comment by llongi** [comment]
Fix merged years ago.
