### ISSUE TITLE
Issue with using DAVIS events from ROS bag in MATLAB ROS toolbox

### ISSUE THREAD

**Issue by sneheshs** [uzh-rpg/rpg_dvs_ros#42]
Hi,

We have ROS bag files with IMU, image, and events data in one bag file from DAVIS 240B. Everything else loads fine with rosbag function in the MATLAB toolbox. However, when trying to decode /dvs/events messages the toolbox is not able to handle it as it seems ros bag stores it in custom data type. We used the dvs_msg folder with rosgenmsg function in the toolbox to generate custom data support. However, this step does not seem to work due to the EventArrayRule.bmr file defined in the package.xml. MATLAB ROS toolbox is not able to handle this. Can you please advise how we might be able to get this hurdle? The goal is to be able to read the events in MATLAB via this ROS toolbox.

Best,
Snehesh

**Comment by eliasm** [comment]
This seems to be identical to #41.
