### ISSUE TITLE
catkin build davis_ros_driver error

### ISSUE THREAD

**Issue by shmm91** [uzh-rpg/rpg_dvs_ros#66]
The platform is ubuntu16.04 , ROS is Kinetic. 
When I catkin build davis_ros_driver, it prompts this:

[ 71%] Built target davis_ros_driver_nodelet
/home/uavlab/dvs_ws/devel/lib/libcaer.solibusb_strerror
collect2: error: ld returned 1 exit status
CMakeFiles/davis_ros_driver.dir/build.make:260: recipe for target '/home/uavlab/dvs_ws/devel/lib/davis_ros_driver/davis_ros_driver' failed
make[2]: *** [/home/uavlab/dvs_ws/devel/lib/davis_ros_driver/davis_ros_driver] Error 1
CMakeFiles/Makefile2:113: recipe for target 'CMakeFiles/davis_ros_driver.dir/all' failed
make[1]: *** [CMakeFiles/davis_ros_driver.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2
[davis_ros_driver] <== '/home/uavlab/dvs_ws/build/davis_ros_driver/build_env.sh /usr/bin/make --jobserver-fds=3,6 -j' failed with return code '2'
                                                                                 
Failed   <== davis_ros_driver [ 0.6 seconds ]                                   
[build] There were '1' errors:                                                  

Failed to build package 'davis_ros_driver' because the following command:

# Command to reproduce:
cd /home/uavlab/dvs_ws/build/davis_ros_driver && /home/uavlab/dvs_ws/build/davis_ros_driver/build_env.sh /usr/bin/make --jobserver-fds=3,6 -j; cd -

# Path to log:
cat /home/uavlab/dvs_ws/build/build_logs/davis_ros_driver.log

Exited with return code: 2

Please give me advise, thank you!!!

**Comment by llongi** [comment]
Looks like a linking error related to libusb_strerror and libcaer (see also #68).
Official libcaer build is now used, see README for further details.
