### ISSUE TITLE
Bug when using grayscale display_method

### ISSUE THREAD

**Issue by fjperezgrau** [uzh-rpg/rpg_dvs_ros#73]
When selecting grayscale display_method, the output image is constantly flashing, most likely due to collision of the image publishers in both images and events callbacks.
In renderer.cpp, the flag `used_last_image_` is never set to true in the case of grayscale, so lines 150-151 could instead be [this](https://gist.github.com/fjperezgrau/47264d650539a1db0eaef24660d1f482), in a similar way as it is done in the case of red-blue display_method.

**Comment by guillermogb** [comment]
Thanks. Addressed here: https://github.com/uzh-rpg/rpg_dvs_ros/pull/74
