### ISSUE TITLE
No instructions for recording data

### ISSUE THREAD

**Issue by ashishrao7** [uzh-rpg/rpg_dvs_ros#82]
I was able to get the packages running according to the instructions in the README. However, I couldn't find instructions on how to record the event, image and IMU data the DAVIS into a file. Could someone please tell how it is done?

**Comment by guillermogb** [comment]
Hi,
Did you take a look at the capabilities of ROS?
http://wiki.ros.org/rosbag/Tutorials/Recording%20and%20playing%20back%20data

`rosbag record /dvs/events /dvs/image_raw /dvs/imu`

**Comment by ashishrao7** [comment]
Oh should I have realized that its published to a topic. Thanks
