### ISSUE TITLE
dvs_calibration build failed with ''cv::CirclesGridFinderParameters’ has not been declared"

### ISSUE THREAD

**Issue by Helloworld-Le** [uzh-rpg/rpg_dvs_ros#89]
Hi，
errors as:

....../dvs_calibration/src/circlesgrid.cpp: In member function ‘bool CirclesGridFinder::isDetectionCorrect()’:
/home/le/sim_ws/src/rpg_dvs_ros/dvs_calibration/src/circlesgrid.cpp:666:14: **_error_: ‘cv::CirclesGridFinderParameters’ has not been declared**
     case cv::CirclesGridFinderParameters::SYMMETRIC_GRID:
              ^~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/le/sim_ws/src/rpg_dvs_ros/dvs_calibration/src/circlesgrid.cpp:686:14: **_error_: ‘cv::CirclesGridFinderParameters’ has not been declared**
     case cv::CirclesGridFinderParameters::ASYMMETRIC_GRID:
              ^~~~~~~~~~~~~~~~~~~~~~~~~~~
make[2]: *** [CMakeFiles/camera_dvs.dir/src/circlesgrid.cpp.o] Error 1
make[1]: *** [CMakeFiles/camera_dvs.dir/all] Error 2

best，
Luke

**Comment by Tobias-Fischer** [comment]
I fixed this problem as follows:
```
diff --git a/dvs_calibration/src/circlesgrid.cpp b/dvs_calibration/src/circlesgrid.cpp
index 0de1dd1..de69f46 100644
--- a/dvs_calibration/src/circlesgrid.cpp
+++ b/dvs_calibration/src/circlesgrid.cpp
@@ -663,7 +663,7 @@ bool CirclesGridFinder::isDetectionCorrect()
 {
   switch (parameters.gridType)
   {
-    case cv::CirclesGridFinderParameters::SYMMETRIC_GRID:
+    case CirclesGridFinderParameters::SYMMETRIC_GRID:
     {
       if (holes.size() != patternSize.height)
         return false;
@@ -683,7 +683,7 @@ bool CirclesGridFinder::isDetectionCorrect()
       return vertices.size() == patternSize.area();
     }
 
-    case cv::CirclesGridFinderParameters::ASYMMETRIC_GRID:
+    case CirclesGridFinderParameters::ASYMMETRIC_GRID:
     {
       if (holes.size() < holes2.size() || holes[0].size() < holes2[0].size())
       {
```
