### ISSUE TITLE
Using event messages in real time

### ISSUE THREAD

**Issue by abhijithrb** [uzh-rpg/rpg_dvs_ros#97]
I would like to use the events of the DAVIS sensor for processing in real real time. Can someone please point me towards how I can go about this?
Thanks

**Comment by wujihua628** [comment]
Hello, I also want to use the event camera for real-time processing.  (Real-time detection, tracking, obstacle avoidance)

What should I do with the event camera ? Can you tell me how you use the event camera for real-time processing？

Thanks

**Comment by ahelamin** [comment]
Did you find a solution for this?
